module.exports = {
  data: [
    {
      id: 1,
      title: 'Allspices powder',
      price: 600,
      description: 'Allspices powder',
      category: 'powder',
      image: '/assets/images/products/allspice-powder.png',
    },
    {
      id: 2,
      title: 'Cinnamon Sticks Spice',
      price: 200,
      description: 'Cinnamon Sticks Spice',
      category: 'grounded',
      image: '/assets/images/products/cinnamon-sticks-spice.png',
    },
    {
      id: 3,
      title: 'Dry Mint Leaves',
      price: 600,
      description: 'Dry Mint Leaves',
      category: 'grounded',
      image: '/assets/images/products/dry-mint-leaves.png',
    },
    {
      id: 4,
      title: 'Fennel Seeds Spice',
      price: 250,
      description: 'Fennel Seeds Spice',
      category: 'grounded',
      image: '/assets/images/products/fennel-seeds-spice.png',
    },
    {
      id: 5,
      title: 'Garam Masala',
      price: 800,
      description: 'Garam Masala',
      category: 'seeds',
      image: '/assets/images/products/garam-masala.png',
    },
    {
      id: 6,
      title: 'Masala Seasonning',
      price: 600,
      description: 'Masala Seasonning',
      category: 'seeds',
      image: '/assets/images/products/masala-seasoning.png',
    },
    {
      id: 7,
      title: 'Mix Masala',
      price: 500,
      description: 'Mix Masala',
      category: 'grounded',
      image: '/assets/images/products/mix-masala.png',
    },
    {
      id: 8,
      title: 'Oregano Spice',
      price: 600,
      description: 'Oregano Spice',
      category: 'seeds',
      image: '/assets/images/products/oregano-spice.png',
    },
    {
      id: 9,
      title: 'Special Condiment',
      price: 400,
      description: 'Special Condiment',
      category: 'seeds',
      image: '/assets/images/products/special-condiment.png',
    },
    {
      id: 10,
      title: 'Spice Tea',
      price: 400,
      description: 'Spice Tea',
      category: 'seeds',
      image: '/assets/images/products/spice-tea.png',
    },
    {
      id: 11,
      title: 'Star Anise Powder Spices',
      price: 500,
      description: 'Star Anise Powder Spices',
      category: 'seeds',
      image: '/assets/images/products/star-anise-powder-spices.png',
    },
    {
      id: 12,
      title: 'Turmeric Spice Powder',
      price: 500,
      description: 'Turmeric Spice Powder',
      category: 'seeds',
      image: '/assets/images/products/turmeric-spice-powder.png',
    },
  ],
};
